### ISSUE TITLE
implementation in extract_patches.so

### ISSUE THREAD

**Issue by vra** [zhuccly/GlomFace-Face-Alignment#1]
Hi @zhuccly ,Thanks for opening source the code. Could you give any detail about implementation in `extract_patches.so`, which extract patches from each landmark of face, Thanks!

**Comment by zhuccly** [comment]
Hi, thanks for your interest. This implementation of extract_patches.so can be found at https://github.com/zhuccly/SRN/blob/main/extract_patches.cc.. Or you can use the "extract_patches" function of Menpo project https://www.menpo.org/.

**Comment by zhuccly** [comment]
> Hi, thanks for your interest. This implementation of extract_patches.so can be found at https://github.com/zhuccly/SRN/blob/main/extract_patches.cc.. Or you can use the "extract_patches" function of Menpo project https://www.menpo.org/.

**Comment by vra** [comment]
HI @zhuccly , Thanks for the response, I will try it 👍
